spring:
  application:
    name: account-manager
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb://localhost:27017/user-db

server:
  port: 8081
  servlet:
    context-path: /account-manager

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
