spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: account-manager
          uri:
            http://localhost:8081
          predicates:
            - Path=/account-manager/**
server:
  port: 8762
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
